---
- hosts: "{{ deployIp }}"
  remote_user: root
  tasks:
    - file: "path=/app/jar/{{ artifactId }} state=directory"
      delegate_to: localhost
    - name: copy to dest
      copy:
        src: "/app/jar/{{ artifactId }}/"
        dest: "/app/jar/{{ artifactId }}/"
    - name: delete local package
      file: "path=/var/app/{{ artifactId }} state=absent force=yes"
      delegate_to: localhost
    - name: restart nginx server
      service:
        name: nginx
        state: restarted
